export const ENDPOINTS = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/signup",
  VERIFY: "/auth/email/verify",
  RESEND_OTP: "/auth/email/resend",
  FORGOT_PASSWORD: "/auth/password/forgot",
  RESET_PASSWORD: "/auth/password/forgot/verify",
  ONBOARDING: "/auth/onboarding",
  ME: "/auth/me",
  PROFILE: "/auth/profile",
  LOGOUT: "/auth/logout",
  INTERFACE: "/auth/interface",
  MFA_SETUP: "/auth/mfa/setup",
  MFA_CONFIRM: "/auth/mfa/confirm",
  MFA_DISABLE: "/auth/mfa/disable",
  MFA_VERIFY: "/auth/mfa/verify",
  SESSIONS: "/auth/sessions",
  SESSIONS_REVOKE: "/auth/sessions/revoke",
  SESSIONS_REVOKE_ALL: "/auth/sessions/revoke-all",
} as const;
