"use client";

import { FormProvider } from "react-hook-form";
import Link from "next/link";
import { Turnstile } from "@marsidev/react-turnstile";
import { ShieldCheck, Loader2, ArrowLeft, KeyRound, Smartphone } from "lucide-react";

import { ROUTES } from "@/core/config";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/shared/components/ui/input-otp";

import { OAuthProviders } from "../primitives";
import LoginFormFields from "./login-form-fields";

import { useLoginForm } from "@/modules/auth/hooks";
import { TURNSTILE_SITE_KEY } from "@/core/config";

// ----------------------------------------------------------------------

export default function LoginForm() {
  const {
    methods,
    onSubmit,
    turnstileRef,
    isSubmitting,
    turnstileToken,
    onCaptchaSuccess,
    onCaptchaExpire,
    mfaRequired,
    mfaMode,
    setMfaMode,
    otpCode,
    setOtpCode,
    recoveryCode,
    setRecoveryCode,
    isVerifyingMfa,
    onVerifyMfaSubmit,
    onBackToLogin,
  } = useLoginForm();

  const canVerify = isVerifyingMfa
    ? false
    : mfaMode === "recovery"
      ? recoveryCode.trim().length === 9
      : otpCode.length === 6;

  if (mfaRequired) {
    return (
      <div className="space-y-6">
        <header className="space-y-1 text-center">
          <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-purple-100 dark:bg-purple-950/60 text-purple-600 dark:text-purple-400 mb-2">
            <ShieldCheck className="size-6" />
          </div>
          <h2 className="text-[1.75rem] font-bold tracking-tight text-slate-900 dark:text-zinc-50 sm:text-[2rem]">
            Two-Factor Verification
          </h2>
          <p className="mx-auto max-w-sm text-sm leading-6 text-slate-600 dark:text-zinc-400">
            {mfaMode === "recovery"
              ? "Use a recovery code to access your account if you don't have your authenticator app."
              : "Enter the 6-digit code generated by your authenticator app."}
          </p>
        </header>

        {/* Mode toggle */}
        <div className="flex items-center gap-1 p-1 rounded-full bg-slate-100 dark:bg-zinc-800/70">
          <button
            type="button"
            onClick={() => setMfaMode("otp")}
            disabled={isVerifyingMfa}
            className={`flex-1 h-9 rounded-full flex items-center justify-center gap-1.5 text-sm font-medium transition-colors hover:cursor-pointer disabled:opacity-60 ${
              mfaMode === "otp"
                ? "bg-white dark:bg-zinc-900 text-slate-900 dark:text-zinc-50 shadow-sm"
                : "text-slate-500 dark:text-zinc-400"
            }`}
          >
            <Smartphone className="size-4" />
            <span>Authenticator</span>
          </button>
          <button
            type="button"
            onClick={() => setMfaMode("recovery")}
            disabled={isVerifyingMfa}
            className={`flex-1 h-9 rounded-full flex items-center justify-center gap-1.5 text-sm font-medium transition-colors hover:cursor-pointer disabled:opacity-60 ${
              mfaMode === "recovery"
                ? "bg-white dark:bg-zinc-900 text-slate-900 dark:text-zinc-50 shadow-sm"
                : "text-slate-500 dark:text-zinc-400"
            }`}
          >
            <KeyRound className="size-4" />
            <span>Recovery Code</span>
          </button>
        </div>

        <div className="flex flex-col items-center justify-center py-2">
          {mfaMode === "recovery" ? (
            <div className="w-full max-w-sm">
              <Input
                type="text"
                value={recoveryCode}
                onChange={(e) => setRecoveryCode(e.target.value)}
                placeholder="XXXX-XXXX"
                disabled={isVerifyingMfa}
                autoCapitalize="characters"
                autoCorrect="off"
                spellCheck={false}
                className="h-12 w-full rounded-xl border-slate-200 bg-white text-slate-900 text-center font-mono text-base font-semibold tracking-widest uppercase shadow-none placeholder:text-slate-400 focus-visible:border-slate-400 focus-visible:ring-0 dark:bg-zinc-950"
              />
              <p className="mt-2 text-center text-xs text-muted-foreground">
                Recovery codes are single-use and will be invalidated after they are redeemed.
              </p>
            </div>
          ) : (
            <InputOTP
              maxLength={6}
              value={otpCode}
              onChange={setOtpCode}
              disabled={isVerifyingMfa}
            >
              <InputOTPGroup className="gap-2">
                <InputOTPSlot index={0} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
                <InputOTPSlot index={1} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
                <InputOTPSlot index={2} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
                <InputOTPSlot index={3} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
                <InputOTPSlot index={4} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
                <InputOTPSlot index={5} className="size-11 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-950 font-mono text-base font-bold text-center" />
              </InputOTPGroup>
            </InputOTP>
          )}
        </div>

        <div className="flex flex-col gap-3">
          <Button
            type="button"
            onClick={onVerifyMfaSubmit}
            disabled={!canVerify}
            className="h-11 w-full rounded-full bg-primary text-[15px] font-semibold text-white shadow-none hover:bg-primary-hover flex items-center justify-center gap-2 hover:cursor-pointer disabled:opacity-50"
          >
            {isVerifyingMfa ? (
              <>
                <Loader2 className="size-4 animate-spin" />
                <span>Verifying...</span>
              </>
            ) : (
              <span>Verify & Continue</span>
            )}
          </Button>

          <Button
            type="button"
            variant="ghost"
            onClick={onBackToLogin}
            disabled={isVerifyingMfa}
            className="h-10 w-full rounded-full text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-800 flex items-center justify-center gap-2 text-sm hover:cursor-pointer"
          >
            <ArrowLeft className="size-4" />
            <span>Back to login</span>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <>
      <header className="space-y-1 text-center">
        <h2 className="text-[2rem] font-semibold tracking-tight text-slate-900 sm:text-[2.15rem]">
          Welcome back
        </h2>

        <p className="mx-auto max-w-sm text-sm leading-6 text-slate-600">
          Sign in to continue where you left off.
        </p>
      </header>

      <OAuthProviders />

      <FormProvider {...methods}>
        <form onSubmit={onSubmit} className="flex flex-col gap-5">
          <LoginFormFields />

          <Turnstile
            ref={turnstileRef}
            siteKey={TURNSTILE_SITE_KEY || ""}
            // options={{ size: "invisible" }}
            onSuccess={onCaptchaSuccess}
            onExpire={onCaptchaExpire}
          />

          <Button
            type="submit"
            className="h-11 w-full rounded-full bg-primary text-[15px] font-semibold text-white shadow-none hover:bg-primary-hover"
            disabled={isSubmitting || !turnstileToken}
          >
            {isSubmitting ? "Logging in..." : "Continue"}
          </Button>

          <p className="text-center text-sm text-slate-500">
            Don&apos;t have an account?{" "}
            <Link
              href={ROUTES.AUTH.REGISTER}
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              Register
            </Link>
          </p>
        </form>
      </FormProvider>
    </>
  );
}
