services:
  db_test:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ../apps/backend/env/.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "6070:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_test_data:
