services:
  db_staging:
    extends:
      file: docker-compose.base.yml
      service: db
    container_name: chhoto_db_staging
    env_file:
      - ../apps/backend/env/.env.staging
    ports:
      - "5432:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  redis_staging:
    extends:
      file: docker-compose.base.yml
      service: redis
    container_name: chhoto_redis_staging
    ports:
      - "6379:6379"
    volumes:
      - redis_staging_data:/data

  backend_staging:
    extends:
      file: docker-compose.base.yml
      service: backend
    image: chhoto-backend:staging
    container_name: chhoto_backend_staging
    env_file:
      - ../apps/backend/env/.env.staging
    ports:
      - "8000:8000"
    depends_on:
      db_staging:
        condition: service_healthy
      redis_staging:
        condition: service_healthy
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  background_worker_staging:
    extends:
      file: docker-compose.base.yml
      service: background_worker
    image: chhoto-backend:staging
    container_name: chhoto_worker_staging
    env_file:
      - ../apps/backend/env/.env.staging
    depends_on:
      db_staging:
        condition: service_healthy
      redis_staging:
        condition: service_healthy
    command: uv run dramatiq src.shared.infrastructure.tasks.registry
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend_staging:
    extends:
      file: docker-compose.base.yml
      service: frontend
    image: chhoto-frontend:staging
    container_name: chhoto_frontend_staging
    env_file:
      - ../apps/frontend/.env.staging
    ports:
      - "3000:3000"
    depends_on:
      - backend_staging
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  chhoto_network:
    name: chhoto_network
    driver: bridge
