services:
  db_test:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chhoto_db_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "6070:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chhoto_db_test"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_test_data:
