services:
  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    container_name: chhoto_backend_staging
    env_file:
      - ../apps/backend/env/.env.staging
    environment:
      - ENVIRONMENT=staging
    ports:
      - "8000:8000"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  background_worker:
    extends:
      file: docker-compose.base.yml
      service: background_worker
    container_name: chhoto_worker_staging
    env_file:
      - ../apps/backend/env/.env.staging
    environment:
      - ENVIRONMENT=staging
    depends_on:
      - backend
    command: dramatiq src.shared.infrastructure.tasks.registry
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    extends:
      file: docker-compose.base.yml
      service: frontend
    container_name: chhoto_frontend_staging
    env_file:
      - ../apps/frontend/.env.staging
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
