app.chhoto.tech {

	# Block auth routes on the app domain
	@auth path /auth*
	respond @auth 404

	reverse_proxy localhost:3000
}

# Authentication domain
auth.chhoto.tech {

	# Don't rewrite Next.js assets
	@next path /_next/*
	handle @next {
		reverse_proxy localhost:3000
	}

	# Don't rewrite common static files
	@static {
		path /favicon.ico
		path /robots.txt
		path /sitemap.xml
		path /manifest.json
		path /apple-touch-icon.png
		path /assets/*
	}

	handle @static {
		reverse_proxy localhost:3000
	}

	@alreadyAuth path /auth*
	handle @alreadyAuth {
		reverse_proxy localhost:3000
	    }

	# Rewrite everything else to /auth/*
	handle {
		rewrite * /auth{uri}
		reverse_proxy localhost:3000
	}
}

go.chhoto.tech {
    rewrite * /api/v1/link/redirect{uri}
    reverse_proxy localhost:8000
}

api.chhoto.tech {
    reverse_proxy localhost:8000
}
