app.chhoto.tech {

    # Block auth routes
    @auth path /auth*
    respond @auth 404

    reverse_proxy localhost:3000
}

auth.chhoto.tech {

    # Rewrite everything to /auth/*
    uri prepend /auth

    reverse_proxy localhost:3000
}
